version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.9-management
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672

  book:
    container_name: book-service
    image: book
    build: .
    restart: on-failure
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE: postgres:5432
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    volumes: # NOTE: choose using local build or pre-built image (remove the volumes if pre-built)
      - ./build/libs/book.jar:/book.jar
    ports:
      - 8081:8081
volumes:
  postgres-data: