server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

spring:
  application:
    name: book-service

  config:
    import: optional:configserver:http://localhost:8082
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
    config:
      label: latest
      name: book
      discovery:
        enabled: true
        service-id: config-service


  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root777
    properties:
      schema: books
  datasource:
    driver-class-name: org.postgresql.Driver

  liquibase:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: root777
    change-log: classpath:db.migration/db.changelog-master.yml
    enabled: true
    default-schema: books


application:
  mock-api: https://jsonplaceholder.typicode.com/posts
